---
- name: install xorg
  apt:
    name: xorg
    state: present
  become: yes

- name: install i3
  apt:
    name: i3
    state: present
  become: yes

- name: i3 directory
  file: path=~/.config/i3 state=directory

- name: i3 config
  template: src=templates/i3/config dest=~/.config/i3/config

- name: i3status directory
  file: path=~/.config/i3status state=directory

- name: i3status config
  template: src=templates/i3status/config dest=~/.config/i3status/config

- name: install firefox
  apt:
    name: firefox-esr
    state: present
  become: yes

- name: install rxvt-unicode
  apt:
    name: rxvt-unicode
    state: present
  become: yes

